### ISSUE TITLE
Fullpage.js autscrolling still on on mobile

### ISSUE THREAD

**Issue by laura-barluzzi** [ascoderu/ascoderu.github.io#5]
On a mobile we want to disable the autoscroll within a fullpage section. This because if the content of a section is longer than the current screen view, the page slides down to the bottom of the section. This makes it impossible to read the top part of content placed in the top of the section.

**Comment by c-w** [comment]
Resolved via #7

**Comment by c-w** [comment]
NB: I noticed two small issues with this which were fixed in https://github.com/ascoderu/ascoderu.github.io/commit/4a6e545acbaf926a2779317c435ef1eed3b3c14f:

1. Setting both responseHeight and responsiveWidth always disabled fullPage.js
2. The "next page" buttons were still shown but not functional.
